- name: Configure TF2 Server
  hosts: tf2_server
  become: yes
  vars:
    tf2_env:
      SRCDS_TOKEN: "{{ srcds_token }}"
      SRCDS_RCONPW: "{{ srcds_rconpw }}"
      SRCDS_PW: "{{ srcds_pw }}"
      SRCDS_STARTMAP: "{{ srcds_startmap }}"
      SRCDS_HOSTNAME: "{{ srcds_hostname }}"
      SRCDS_SECURED: "{{ srcds_secured | string }}"
  tasks:
    - name: Run TF2 server Docker container
      docker_container:
        name: tf2-dedicated
        image: cm2network/tf2
        state: started
        recreate: yes
        network_mode: host
        env: "{{ tf2_env }}"
        interactive: yes
        tty: yes
        detach: yes

    - name: Restart TF2 server Docker container
      docker_container:
        name: tf2-dedicated
        state: started
        env: "{{ tf2_env }}"
        restart: yes
      tags: restart