- name: Configure TF2 Server
  hosts: tf2_server
  become: yes
  vars:
    tf2_env:
      RCON_PASSWORD: "{{ rcon_password }}"
      SERVER_HOSTNAME: "{{ server_hostname }}"
  tasks:
    - name: Run TF2 server Docker container
      docker_container:
        name: tf2-dedicated
        image: ghcr.io/melkortf/tf2-base
        state: started
        recreate: yes
        network_mode: host
        env: "{{ tf2_env }}"
        interactive: yes
        tty: yes
        detach: yes

    - name: Restart TF2 server Docker container
      docker_container:
        name: tf2-dedicated
        state: started
        env: "{{ tf2_env }}"
        restart: yes
      tags: restart