- name: Configure TF2 Server
  hosts: tf2_server
  become: yes
  tasks:
    - name: Run TF2 server Docker container
      docker_container:
        name: tf2-dedicated
        image: cm2network/tf2
        state: started
        recreate: yes
        network_mode: host
        env:
          SRCDS_TOKEN: "{{ lookup('env', 'SRCDS_TOKEN') }}"
          SRCDS_RCONPW: "{{ lookup('env', 'SRCDS_RCONPW') }}"
          SRCDS_PW: "{{ lookup('env', 'SRCDS_PW') }}"
          SRCDS_STARTMAP: "{{ lookup('env', 'SRCDS_STARTMAP') }}"
          SRCDS_HOSTNAME: "{{ lookup('env', 'SRCDS_HOSTNAME') }}"
          SRCDS_SECURED: "{{ lookup('env', 'SRCDS_SECURED') }}"
        interactive: yes
        tty: yes