- name: Configure TF2 Server
  hosts: tf2_server
  become: yes
  vars:
    tf2_env:
      RCON_PASSWORD: "{{ rcon_password }}"
      SERVER_HOSTNAME: "{{ server_hostname }}"
  tasks:
    - name: Download TF2 maps
      ansible.builtin.command: aws s3 sync s3://upfast-tf2-maps/ /home/ec2-user/maps

    - name: Run TF2 server Docker container
      docker_container:
        name: tf2-dedicated
        image: ghcr.io/melkortf/tf2-base
        state: started
        recreate: yes
        network_mode: host
        env: "{{ tf2_env }}"
        interactive: yes
        tty: yes
        detach: yes
        volumes:
          - "/home/ec2-user/maps:/home/tf2/server/tf/maps"

    - name: Restart TF2 server Docker container
      docker_container:
        name: tf2-dedicated
        state: started
        env: "{{ tf2_env }}"
        restart: yes
      tags: 
        - never
        - restart